name: worship_connect
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.3
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  google_fonts: ^2.2.0
  flutter_riverpod: ^1.0.3
  nanoid: ^1.0.0
  intl: ^0.17.0
  simple_gradient_text: ^1.2.2
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

